name: Feature/Bug CI

on:
  push:
    branches-ignore:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  microservices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'
      - name: Build Package
        run: mvn -B package --file microservices/ai-cpa-ms/pom.xml

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Build App
        run: |
          cd frontend/ai-cpa-ui
          npm install
          npm run build

  data-science:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build and Test App
        run: |
          cd data-science/ai-cpa-ds
          pip install -r requirements.txt
          pytest